server:
  port: 8056

localeTag: "ru-RU"

telegram-bot:
  botUserName: ${BOT_USERNAME}
  botToken: ${BOT_TOKEN}
  webHookPath: ${WEBHOOK_PATH}

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Bot?useUnicode=true&serverTimezone=Europe/Kiev
    username: mysql
    password: mysql
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true