package com.home.WeatherBot.botApi;

public enum BotState {
    WELCOME_MENU,
    SHOW_HELP_MENU,

    FILLING_WEATHER_REQUEST,
    ASK_CITY,
    GET_WEATHER_BY_CITY,

    ADD_SUBSCRIPTION,
    DELETE_SUBSCRIPTION,
    GET_SUBSCRIPTION_BY_TIME,
    GET_SUBSCRIPTION_BY_CITY,
    ASK_TIME_BY_SUBSCRIPTION,
    ASK_CITY_BY_SUBSCRIPTION,

    SHOW_MAIN_MENU,

    SEND
}
